/**
 * Deterministic rendering of a {@link TestPlan} into Jest + React Testing
 * Library source.
 *
 * The LLM's output stays confined to the plan schema; everything that becomes
 * code on disk goes through these templates, so re-planning produces meaningful
 * diffs and house style is enforced here, not by the model.
 *
 * The emitted suite is RED: every case carries a `bddPending()` marker
 * (imported from the shared `sdd-setup`) as its FIRST body statement. Until the
 * implementer deletes that one line per test, the test throws
 * `PendingSpecError` and fails — the Jest analogue of Python's
 * `pytest.mark.bdd_pending`. This makes "not yet implemented" a build failure,
 * not a silent skip (`it.todo`) or an inverted pass. The real assertions sit
 * right below the marker, so once it is removed the test exercises the
 * component/hook for real.
 *
 * The default output targets a Jest harness: ambient globals
 * (`describe`/`it`/`expect`/`jest` — no test-runner import),
 * `@testing-library/react` + `@testing-library/user-event`, and jest-dom
 * matchers registered by the consuming project's setup file. Point
 * {@link renderTests} at a different harness via {@link RenderConfig} if your
 * app uses Vitest instead.
 *
 * A faithful twin of `pyllm.bdd.renderer`, retargeted to `.test.tsx`.
 */

import type { TestCase, TestPlan } from "./schema.js";

/**
 * The test-runner harness the generated suite targets. Defaults to a Jest + RTL
 * shape (ambient globals, `jest.fn()`).
 */
export interface RenderConfig {
  /** "jest" (ambient globals, default) or "vitest" (imports + `vi`). */
  runner: "jest" | "vitest";
  /**
   * "web" (default, DOM React Testing Library) or "native" (React Native
   * Testing Library). On "native" the harness imports come from
   * `@testing-library/react-native` and there is no DOM `userEvent`.
   */
  platform: "web" | "native";
  /** Import specifier for the shared SDD harness (the `bddPending` marker). */
  setupModule: string;
  /**
   * Extra import lines to inject into every suite (e.g. project dependencies
   * pulled from `reactullm.config.json`), emitted verbatim after the harness
   * imports and before the spec's own `api.imports`.
   */
  extraImports?: readonly string[];
  /**
   * Provider import lines for the generated `renderWithProviders` wrapper in
   * `renderSetup()`. Emitted verbatim; the wrapper body is left as a TODO for
   * the implementer to compose.
   */
  providers?: readonly string[];
}

export const DEFAULT_RENDER_CONFIG: RenderConfig = {
  runner: "jest",
  platform: "web",
  setupModule: "./sdd-setup",
};

/** The RTL package the generated suite imports render/screen/etc. from. */
function rtlModule(platform: RenderConfig["platform"]): string {
  return platform === "native" ? "@testing-library/react-native" : "@testing-library/react";
}

const GENERATED_HEADER = (feature: string): string =>
  `// Generated by react-sdd from feature: ${feature}
// These tests are the specification. Do not edit them during implementation;
// regenerate from the .toml spec instead. Each test's first line is a
// bddPending() marker — delete exactly that line as you make the test pass.`;

/** camelCase-ish identifier for a fixture helper; deduped by _unique. */
function identifier(name: string, prefix: string): string {
  let ident = name
    .trim()
    .replace(/[^0-9a-zA-Z_$]+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (prefix && !ident.startsWith(prefix)) {
    ident = ident ? prefix + ident.charAt(0).toUpperCase() + ident.slice(1) : `${prefix}Case`;
  }
  if (!ident || /^[0-9]/.test(ident)) ident = `${prefix || "helper"}Case`;
  return ident;
}

function unique(name: string, taken: Set<string>): string {
  let candidate = name;
  let n = 2;
  while (taken.has(candidate)) {
    candidate = `${name}_${n}`;
    n += 1;
  }
  taken.add(candidate);
  return candidate;
}

function bodyLines(testCase: TestCase): string[] {
  const lines: string[] = [];
  // The red marker — always the first statement, always deletable as one line.
  lines.push("bddPending(); // TODO: delete this line when the test passes");
  if (testCase.covers.length) lines.push(`// Covers: ${testCase.covers.join(", ")}`);
  if (testCase.notes) lines.push(`// ${testCase.notes}`);
  if (testCase.given.length) {
    lines.push(`// Given: ${testCase.scenario}`);
    lines.push(...testCase.given);
  }
  lines.push("// When");
  // An act that is itself handled in `given` (pure render assertion sets when
  // to "None") renders without the `result` assignment.
  lines.push(testCase.when.trim() === "None" ? "// (act performed in arrange above)" : `const result = ${testCase.when};`);
  if (testCase.then.length) {
    lines.push("// Then");
    // `then` entries are already complete RTL assertion statements.
    lines.push(...testCase.then.map((expr) => (expr.trim().endsWith(";") ? expr : `${expr};`)));
  }
  // `result` may be unused in a pure-render case; keep TS/lint quiet.
  if (testCase.when.trim() !== "None") lines.push("void result;");
  return lines;
}

function indent(lines: string[], depth: number): string[] {
  const pad = "  ".repeat(depth);
  return lines.map((l) => (l.length ? pad + l : l));
}

/** Render a complete, syntactically valid, red Jest (or Vitest) + RTL module. */
export function renderTests(plan: TestPlan, config: RenderConfig = DEFAULT_RENDER_CONFIG): string {
  const out: string[] = [];
  out.push(GENERATED_HEADER(plan.feature));
  out.push("");
  // Jest globals (describe/it/expect/jest) are ambient — no runner import. The
  // project's jest.setup.js already registers @testing-library/jest-dom.
  if (config.runner === "vitest") {
    out.push('import { describe, it, expect, vi } from "vitest";');
  }
  const rtl = rtlModule(config.platform);
  if (config.platform === "native") {
    // React Native Testing Library: no DOM; fireEvent replaces DOM userEvent,
    // renderHook lives in the same package, no screen/waitFor DOM semantics.
    out.push(`import { render, screen, renderHook, act, waitFor, fireEvent } from ${JSON.stringify(rtl)};`);
  } else {
    out.push(`import { render, screen, renderHook, act, waitFor } from ${JSON.stringify(rtl)};`);
    out.push('import userEvent from "@testing-library/user-event";');
  }
  out.push(`import { bddPending } from ${JSON.stringify(config.setupModule)};`);
  for (const imp of config.extraImports ?? []) out.push(imp);
  for (const imp of plan.api.imports) out.push(imp);
  out.push("");

  const taken = new Set<string>();

  for (const fixture of plan.fixtures) {
    const name = unique(identifier(fixture.name, ""), taken);
    const body = fixture.body.length ? fixture.body : ["return undefined;"];
    out.push(`function ${name}() {`);
    out.push(...indent(body, 1));
    out.push("}");
    out.push("");
  }

  out.push(`describe(${JSON.stringify(plan.feature)}, () => {`);
  plan.cases.forEach((testCase) => {
    const asyncKw = testCase.isAsync ? "async " : "";
    if (testCase.edgeCase) out.push(`  // Edge case derived from: ${testCase.scenario}`);
    out.push(`  it(${JSON.stringify(testCase.testName)}, ${asyncKw}() => {`);
    out.push(...indent(bodyLines(testCase), 2));
    out.push("  });");
    out.push("");
  });
  out.push("});");

  return out.join("\n") + "\n";
}

/**
 * The shared setup / test-utils file for the output directory — the conftest
 * analogue. Written ONCE per output directory.
 *
 * It exports `bddPending()` (the red marker every generated test calls until
 * implemented) and a `renderWithProviders` custom render that the implementer
 * wires to the app's real providers (router, store, theme). Generated tests
 * import `render` from the RTL package directly; swap to `renderWithProviders`
 * here when a case needs providers.
 *
 * Platform-aware: on `platform: "native"` it imports from
 * `@testing-library/react-native`; otherwise from `@testing-library/react`. Any
 * `config.providers` import lines are emitted at the top for the wrapper to use.
 *
 * Runner-agnostic: it references no test-runner globals, so it works under a
 * Jest harness (jest-dom matchers come from the consuming project's own setup
 * file, not from here) and equally under Vitest.
 */
export function renderSetup(config: RenderConfig = DEFAULT_RENDER_CONFIG): string {
  const rtl = rtlModule(config.platform);
  const providerImports = (config.providers ?? []).map((p) => p + "\n").join("");
  return `// Generated by react-sdd — shared SDD test harness (the conftest analogue).
// Written once per output directory; safe to extend by hand.
import type { ReactElement, ReactNode } from "react";
import { render, type RenderOptions } from ${JSON.stringify(rtl)};
${providerImports}
/**
 * The red marker. Every generated test calls this on its first line so a
 * not-yet-implemented spec FAILS (loudly) instead of silently passing or being
 * skipped. Delete that one line from a test as you make it pass.
 */
export class PendingSpecError extends Error {
  constructor() {
    super(
      "SDD pending spec: this test is generated from a .toml spec and is red " +
        "until implemented. Delete the bddPending() line once the test passes.",
    );
    this.name = "PendingSpecError";
  }
}

export function bddPending(): never {
  throw new PendingSpecError();
}

/**
 * Custom render wiring the app's real providers. Wrap children with your
 * router/store/theme providers here, then have a case's 'given' call
 * renderWithProviders(...) instead of render(...).
 */
function Providers({ children }: { children: ReactNode }): ReactElement {
  // TODO: wrap with <MemoryRouter>, <Provider store={...}>, theme, etc.
  return children as ReactElement;
}

export function renderWithProviders(
  ui: ReactElement,
  options?: Omit<RenderOptions, "wrapper">,
) {
  return render(ui, { wrapper: Providers, ...options });
}
`;
}
